[package]
name = "gml"
version = "0.1.0"
authors = ["Russell Johnston <rpjohnst@gmail.com>"]
edition = "2018"

[dependencies]
gml-meta = { path = "meta" }
project = { path = "../project" }
quickdry = "0.1"

[target.wasm32-unknown-unknown.dependencies]
wasm-host = { path = "../wasm-host" }
